services:
  - type: web
    name: voice-translator-offline
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd web && python app_offline.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8081
    plan: free
    autoDeploy: true
    healthCheckPath: /
    region: oregon
