services:
  - type: web
    name: voice-translator-offline
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd web && gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app_offline:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8081
    plan: free
    autoDeploy: true
    healthCheckPath: /